### ISSUE TITLE
Remove from the list "ASN bad for privacy" that offer both CDN and normal hosting

### ISSUE THREAD

**Issue by unixfox** [searxng/searx-space#129]
Since the introduction of https://github.com/searxng/searx-instances/pull/223 we do not allow any instances that are hosted under a CDN.
The current check in searx.space for flagging instances that are hosted under ASN that offer CDN is now not needed anymore as we manually already deny any instances that are using one.

Amazon for example offer CDN services AND normal server hosting, I propose to remove all the ASNs that offer both of these services in order to not falsely classify the public instances that are not under a CDN.

We should still keep the code though and the ASN that are only for CDN services like Cloudflare, this way we can more easily detect the instances that start enable cloudflare after being added to the list.

What do you think @dalf @return42 @mrpaulblack @tiekoetter @ononoki1.

**Comment by nicfab** [comment]
I am getting comments of concern about my instance as it shows up with "privacy issues" with red background. On the one hand, all this demoralizes me for all the effort I put into setting up and maintaining the instance. On the other, it makes me consider whether - under these conditions - it is still worth having a public instance. I did my best to make my instance available to anyone, but I don't want to be prejudiced by problems that - IMHO - do not exist.
 
I know this topic is being discussed, but I would like to bring some of my thoughts to your attention:
1. It is only possible to say that a resource has "**privacy issues**" only if you have firm and irrefutable evidence. Is there firm evidence about what you called "privacy issues"?

2. As far as I am concerned, my instance is physically in the Amazon - AWS data center in Milan (Italy), managed by the following company based in Luxembourg:
AMAZON WEB SERVICES EMEA SARL - 38 Avenue John F. Kennedy, L-1855 Grand Duchy of Luxembourg - R.C.S. **Luxembourg**: B186284 - Share Capital: EUR 25,000 i.v. - VAT NO: LU 26888617 - Company with a sole shareholder
with a **Branch Office - Viale Monte Grappa 3/5, 20124 Milan, Italy** - **Milan Business Register - Milan Office - REA No. 2506640 - Tax Code and VAT No.: 10119840964**. 
So the company is officially registered also in Italy.
Since it is a company based in Europe (Luxembourg with a secondary office in Italy), it must comply with the EU Regulation 2016/679 (GDPR), which provides significant penalties for any violations. **To my knowledge, no sanctions have been issued to the said company**. Could you let me know if you're aware of any sanctions given to the company mentioned above?

3. Given my professional experience (which you can check on the web if you want), I am meticulous about privacy and security, maintaining high profiles on my server.

After these considerations, I invite you to review and reconsider as soon as possible your decision to deem my instance (like others) with "privacy issues".

**Comment by unixfox** [comment]
If you want to get this fixed quicker, feel free to submit a pull request where all the [ASN](https://en.wikipedia.org/wiki/Autonomous_system_(Internet)) that offer normal hosting (servers/VPS for instance) are removed from the list.

You can't take for granted that open source maintainers will fix the issues at your service, the open source spirit is that everyone is free to contribute to the code and if one wants to get an issue fixed quicker he has to contribute by submitting the work that he has done for fixing this issue.
Usually, the projects maintained by open source volunteers are not their main job, they are working on it on their free time. So when there are very few maintainers they focus on the big important issues or on the issues that they personally want to fix.
Please keep that in mind, we are not at your service. We do our best for offering this instance list service for free but as you can see you are not the only one that submitted some issue related to that service: https://github.com/searxng/searx-space/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+

**Comment by nicfab** [comment]
> If you want to get this fixed quicker, feel free to submit a pull request where all the [ASN](https://en.wikipedia.org/wiki/Autonomous_system_(Internet)) that offer normal hosting (servers/VPS for instance) are removed from the list.
> 
> You can't take for granted that open source maintainers will fix the issues at your service, the open source spirit is that everyone is free to contribute to the code and if one wants to get an issue fixed quicker he has to contribute by submitting the work that he has done for fixing this issue. Usually, the projects maintained by open source volunteers are not their main job, they are working on it on their free time. So when there are very few maintainers they focus on the big important issues or on the issues that they personally want to fix. Please keep that in mind, we are not at your service. We do our best for offering this instance list service but as you can see you are not the only one that submitted some issue related to that service: https://github.com/searxng/searx-space/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+

Thank you. 
I will submit a PR.

**Comment by nicfab** [comment]
Just to complete my previous comment, some remarks are below.

> If you want to get this fixed quicker, feel free to submit a pull request where all the [ASN](https://en.wikipedia.org/wiki/Autonomous_system_(Internet)) that offer normal hosting (servers/VPS for instance) are removed from the list.

Probably, I'll try, hoping not to make mistakes due to the fact that I am not a developer.

> You can't take for granted that open source maintainers will fix the issues at your service, the open source spirit is that everyone is free to contribute to the code and if one wants to get an issue fixed quicker he has to contribute by submitting the work that he has done for fixing this issue. 

I know what the open-source spirit is, and I support it but consider that I am not a developer. 
My previous comment had the aim to raise awareness of you an issue that is worrying for me.

> Usually, the projects maintained by open source volunteers are not their main job, they are working on it on their free time. 

I know it.

> So when there are very few maintainers they focus on the big important issues or on the issues that they personally want to fix. 

Of course.

> Please keep that in mind, we are not at your service. 

I never thought so, and I only submitted a request to urge a solution.  
I think there was a misunderstanding. 
I'm sorry you read my comment that way.

> We do our best for offering this instance list service for free but as you can see you are not the only one that submitted some issue related to that service: https://github.com/searxng/searx-space/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+

I know, and usually, I thank you for your work which I appreciate very much. It is not the case that I wrote more than one article on SearXNG to spread how it works, the importance of developer's activities, and the attention to privacy issues.

**Comment by unixfox** [comment]
Resolved in https://github.com/searxng/searx-space/pull/138
