### ISSUE TITLE
Update version parsing

### ISSUE THREAD

**Issue by dalf** [searxng/searx-space#134]
The SearXNG version pattern has changed.

For example `2023.1.22+a8eb9d15` : 
* use `+` instead of `-`
* no leading zero

Currently, on searx.space, the versions are not anymore shorted by year then month.

Related code:
https://github.com/searxng/searx-space/blob/1cdd5543ab478059e4f37757e23afb03c13bc95f/html/main.js#L114-L136

**Comment by unixfox** [comment]
Why this strange idea of removing the leading zero?

If you were to sort the versions using bash, all the months before october would be sorted higher than the months after and including october.

For example, 2023-2-1 would be after 2023-10-1 because the number 2 is higher than 1 in the first digit of the month.

**Comment by dalf** [comment]
> Why this strange idea of removing the leading zero?

Because the public version is also a pip version, and pip doesn't allow anymore leading zero
