### ISSUE TITLE
Certificate column empty on all instances

### ISSUE THREAD

**Issue by tiekoetter** [searxng/searx-space#89]
The certificate column is empty on all listed instances on searx.space

<img width="1439" alt="searx space 2022-01-02 21 39 05" src="https://user-images.githubusercontent.com/77782671/147888989-9b9893dd-7968-474d-bdcb-28881ddd8c74.png">

**Comment by dalf** [comment]
I'm sorry about that.
Some dependencies have changes, and the current code can't fetch the certificate (the commit 1b618f2ce920d27afc3db0741487c48270eca374 is a quick fix).

To fetch the certificates, it requires:
* to use the last version of httpx (instead of the old 0.11.0 version).
* to upgrade [searxstats/common/http.py](https://github.com/searxng/searx-space/blob/1b618f2ce920d27afc3db0741487c48270eca374/searxstats/common/http.py#L85-L138) and [searxstats/common/ssl_info.py](https://github.com/searxng/searx-space/blob/master/searxstats/common/ssl_info.py)

**Comment by dalf** [comment]
From https://github.com/searxng/searx-space/commit/1b618f2ce920d27afc3db0741487c48270eca374#r64431924 ( @not-my-profile ):

https://github.com/searxng/searx-space/blob/1b618f2ce920d27afc3db0741487c48270eca374/searxstats/common/ssl_info.py#L5

> `load_certificate` and `FILETYPE_ASN1` are still used in `update_obj_with_bin` ... which is also the cause of the CI failure:
> 
> ```
> searxstats/common/ssl_info.py:29:15: F821 undefined name 'load_certificate'
> searxstats/common/ssl_info.py:29:32: F821 undefined name 'FILETYPE_ASN1'
> ```
> 
> Is `update_obj_with_bin` never used or why doesn't this matter?
